import type { Manifest } from './engine';
const escape = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function csvCell(s: unknown): string {
  let value = String(s ?? '');
  // Neutralize spreadsheet formulas, including leading whitespace/control variants.
  if (/^\s*[=+@-]/.test(value)) value = "'" + value;
  return '"' + value.replaceAll('"', '""') + '"';
}
export function reports(manifest: Manifest): { csv: string; html: string } {
  const keys = ['id', 'sourcePath', 'status', 'outcome', 'reason', 'sourceSha256', 'outputPath', 'outputSha256', 'payloadSha256', 'payloadPreserved', 'metadataVerified', 'captureAfter', 'offsetAfter', 'sidecarPath', 'sidecarSha256', 'sidecarCaptureEpoch', 'matchConfidence'] as const;
  const csv = '\uFEFF' + keys.map(csvCell).join(',') + '\r\n' + manifest.entries.map(row => keys.map(key => csvCell(row[key])).join(',')).join('\r\n') + '\r\n';
  const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>ArchiveGuard audit</title><style>body{font:15px system-ui;color:#173b34;background:#f5f6f1;margin:32px}h1{font-size:30px}table{border-collapse:collapse;background:white;width:100%}td,th{padding:14px;text-align:left;border-bottom:1px solid #ddd;vertical-align:top}small{display:block;overflow-wrap:anywhere;max-width:600px;color:#546c63}li{margin:10px 0}.wrap{overflow:auto}</style><h1>ArchiveGuard · Verified copy audit</h1><p>${escape(manifest.createdAt)} · ${manifest.summary.repaired} repaired · ${manifest.summary.copied} unchanged copies · ${manifest.summary.excluded} excluded inputs</p><p>Original files were never overwritten. Source SHA-256 records original bytes; repaired output hashes may differ. JPEG content outside EXIF was preserved byte for byte and hashed. GPS coordinates are omitted from this report; existing GPS remains in JPEG copies.</p><div class="wrap"><table><thead><tr><th>Selected input</th><th>Outcome</th><th>Capture time</th><th>Provenance &amp; verification</th></tr></thead><tbody>${manifest.entries.map(row => `<tr><td>${escape(row.sourcePath)}<small>Source SHA-256: ${escape(row.sourceSha256 || 'Not read')}</small></td><td>${escape(row.outcome)}<small>${escape(row.reason)}</small></td><td>${escape(row.captureAfter)} ${escape(row.offsetAfter)}</td><td>${escape(row.sidecarPath || 'No sidecar used')}<small>Output: ${escape(row.outputPath || 'Excluded')}<br>Output SHA-256: ${escape(row.outputSha256 || '—')}<br>Content outside EXIF preserved: ${row.payloadPreserved === true ? 'Verified' : 'Not exported'}<br>Written capture fields: ${row.metadataVerified === true ? 'Verified by two readers' : row.outcome === 'copied' ? 'Byte-identical copy' : 'Not exported'}</small></td></tr>`).join('')}</tbody></table></div><h2>Scope and limitations</h2><ul>${manifest.limitations.map(s => `<li>${escape(s)}</li>`).join('')}</ul></html>`;
  return { csv, html };
}
